Flailing around trying to fix circleci issue- see if ts-mocha works better than --require ts-node/register
https://app.circleci.com/pipelines/github/http4t/http4t/148/workflows/2186bbdd-ccbc-4d6b-ad34-4f533d2595cf/jobs/132

$ NODE_ENV=development mocha --require ts-node/register --exit  'test/**/*.test.ts'
/home/circleci/project/http4t-bidi-eg/node_modules/ts-node/src/index.ts:368
        throw new TypeError(
              ^

TypeError: Unable to require `.d.ts` file.

This is usually the result of a faulty configuration or import. Make sure there is a `.js`, `.json` or another executable extension and loader (attached before `ts-node`) available alongside `index.ts`.

    at getOutput (/home/circleci/project/http4t-bidi-eg/node_modules/ts-node/src/index.ts:368:15)
    ...